name: Test

on:
  push:
    branches:
      - main
      - test**

jobs:
  test-events:
    runs-on: ubuntu-latest
    
    steps:
      - name: Visible Step
        run: |
          echo "Running dispatch trigger..."
          curl --version  # or even just this will show up
          
      - name: Print GitHub Ref
        if: startsWith( "${{ github.ref }}" , 'refs/heads/test' )
        run:  |
          echo "GitHub Ref: ${{ github.ref }}"

